#!/bin/bash

set -euo pipefail

TOP="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" &>/dev/null && pwd 2>/dev/null)"/..

cd "$TOP"

sudo -u pedal git fetch --quiet
HEAD=$(sudo -u pedal git rev-parse HEAD)
ORIGIN=$(sudo -u pedal git rev-parse origin)

if [ "$HEAD" != "$ORIGIN" ]; then
    exit 0
else
    exit 1
fi
