#!/bin/bash

set -euo pipefail

git fetch --quiet
HEAD=$(git rev-parse HEAD)
ORIGIN=$(git rev-parse origin)

if [ "$HEAD" != "$ORIGIN" ]; then
    sudo systemctl stop petal.sc
    git pull
    sudo systemctl start petal.sc
    exit 0
else
    exit 1
fi
